=== lightstalker89/MIT_SAD/first_semester/programing/final_project/drexler/Prototyp/Prototyp/Configuration/ConfigScheme.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://tempuri.org/ConfigScheme.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/ConfigScheme.xsd"
    xmlns:mstns="http://tempuri.org/ConfigScheme.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="1">
        <xs:element name="SourceDirectories" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Directory" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Path"/>
                    <xs:element type="xs:boolean" name="IncludeSubdirectories" />
                    <xs:element name="TargetDirectories">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Directory" maxOccurs="unbounded" minOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Path"/>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="type" use="required"/>
                              <xs:attribute type="xs:string" name="ip" use="optional"/>
                              <xs:attribute type="xs:short" name="port" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ExceptionDirectories">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Directory">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="Path"/>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="type" use="required"/>
                              <xs:attribute type="xs:string" name="ip" use="optional"/>
                              <xs:attribute type="xs:short" name="port" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="type" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <!-- Activate parallel Synchronisation-->
        <xs:element name="ParallelSync" type="xs:boolean" />
        <!-- Default size of a log file -->
        <xs:element name="LogFileSize" type="xs:long" />
        <!-- Sync files with the specified file size per block -->
        <xs:element name="FileSize" type="xs:long" />
        <xs:element name="BlockSize" type="xs:long" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== lightstalker89/MIT_SAD/first_semester/programing/final_project/drexler/Prototyp/Prototyp/Configuration/DefaultConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://www.judo-eisenstadt.at/FHWN ConfigScheme.xsd"
                       xmlns="http://www.judo-eisenstadt.at/FHWN">
  <SourceDirectories>
    <Directory type="Local">
      <Path>C:\Temp</Path>
      <IncludeSubdirectories>True</IncludeSubdirectories>
      <TargetDirectories>
        <Directory type="Local">
          <Path>C:\Test</Path>
        </Directory>
        <!--<Directory type="Shared">
          <Path>\\192.168.1.3\Family\FH_SyncerTest</Path>
        </Directory>-->
        <!--<Directory type="Network" ip="192.168.1.2" port="4000">
          <Path>C:\Test</Path>
        </Directory>-->
      </TargetDirectories>
      <ExceptionDirectories>
        <Directory type="Local">
          <Path>C:\Temp\Neuer Ordner</Path>
        </Directory>
      </ExceptionDirectories>
    </Directory>
  </SourceDirectories>
  
  <FileSize>500</FileSize>
  <BlockSize>200</BlockSize>
  <ParallelSync>False</ParallelSync>
  <LogFileSize>20000</LogFileSize>
</Config>
